name: Phash-rb

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.6'

    steps:
    - uses: actions/checkout@v4
    - name: Install libvips & imagemagick
      run: |
        sudo apt-get update
        # we only need the library
        sudo apt-get install --no-install-recommends libvips imagemagick
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3
    - name: Run the tests
      run: bundle exec rake test
